---
title: Connors RSI
subtitle: Connors RSI is a short-term trading strategy that enters long when RSI(2) is less than 5.
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r libraries}
library(knitr)
library(lattice)
library(purrr)          # For plotting multiple charts at once
library(quantmod)
library(quantstrat)
```

```{r includes}
source("./_R/functions.R")   # for checkBlotterUpdate()
```

 * BTO when RSI(2) < 5 & Cl > SMA(200)
 * STC when Cl > SMA(5)

## Variables

```{r variables}
symbols            <-        c("IWM", "QQQ", "SPY")

# Transaction Details
shares             <-        100                    #' Shares to trade
transaction_fees   <-        10                     #' Cost of trade, abs value

# Indicators
nrsi               <-        2                      #' RSI(2)
rsiThresh          <-        5                      #' RSI(2) threshold
rsiMaType          <-        "SMA"                  #' RSI uses SMA
smaFast            <-        5                      #' SMA(5)
smaFastCol         <-        4                      #' Blue
smaSlow            <-        200                    #' SMA(200)
smaSlowCol         <-        2                      #' Red

# Data params
source             <-        "yahoo"                #' Yahoo, Google, FRED, etc.
init_date          <-        "2009-12-31"           #' start_date - 1 day
start_date         <-        "2010-01-01"           #' Begin trading
end_date           <-        "2015-12-31"           #' End trading
init_equity        <-        100000                 #' Initial equity

# Portfolio, account and strategy names
portfolio.st       <-        "ConnorsRSI"           #' Name of portfolio
account.st         <-        "ConnorsRSI"           #' Name of account
strategy.st        <-        "ConnorsRSI"           #' Name of strategy

# Additional
tz                 <-        "UTC"                  #' Time zone
#' Currency abbr (ISO 4217); set for currency of symbols.
curr               <-        "USD"
adjustment         <-        TRUE
```

## Setup

```{r timezone}
Sys.setenv(TZ = tz)
```

```{r currency}
currency(curr)
```

### Get Symbols

```{r get.symbols}
getSymbols(Symbols           =         symbols, 
           src               =         source, 
           from              =         start_date, 
           to                =         end_date, 
           # Adjust OHLC values for splits and dividencs, etc.
           adjust            =         FALSE)
```

```{r stock}
stock(symbols, 
      currency               =         curr)
```

### Remove objects

```{r rm.objects}
# Remove existing objects to avoid invalid data
rm.strat(portfolio.st)
rm.strat(account.st)
```

### Initalize objects

```{r init.portf}
# Initialize portfolio object
initPortf(name               =         portfolio.st, 
          symbols            =         symbols, 
          initDate           =         init_date)
```

```{r init.acct}
# Initialize account object
initAcct(name                =         account.st, 
         portfolios          =         portfolio.st, 
         initDate            =         init_date, 
         initEq              =         100000)
```

```{r init.orders}
# Set up portfolio
initOrders(portfolio         =         portfolio.st, 
           symbols           =         symbols, 
           initDate          =         init_date)
```

```{r init.strategy}
strategy(strategy.st, 
         store               =         TRUE)
```

## Add Indicators

```{r add.indicators}
# Add SMA(5) `SMA5`
add.indicator(strategy       =         strategy.st,
              # TTR:SMA()
              name           =         "SMA",
              # Parameters for TTR:SMA()
              arguments      =         list(x         =    quote(Cl(mktdata)), 
                                            n         =    smaFast),
              # Var name for indicator
              label          =         "SMA5")

# Add SMA(200) `SMA200`
add.indicator(strategy       =         strategy.st,
              name           =         "SMA",
              arguments      =         list(x         =     quote(Cl(mktdata)),
                                            n         =     smaSlow),
              label          =         "SMA200")

# Add RSI(2) `RSI2`
add.indicator(strategy       =         strategy.st,
              name           =         "RSI",
              # Notice our first parameter is price, not x like in SMA()
              arguments      =         list(price     =     quote(Cl(mktdata)),
                                            n         =     nrsi, 
                                            maType    =     rsiMaType),
              label          =         "RSI2")

# Apply indicators
ind <- applyIndicators(strategy = strategy.st, 
                       mktdata  = OHLC(mktdata))
```

## Add Signals

```{r add.signals}
# Add signal when RSI2 < 5 `RSI2.lt.5`
add.signal(strategy        =          strategy.st,
           name            =          "sigThreshold",
           arguments       =          list(column         =    "RSI2", 
                                           threshold      =    rsiThresh, 
                                           relationship   =    "lt", 
                                           # Only when RSI x< 5
                                           cross          =    TRUE), 
           label           =          "RSI2.lt.5")

# Close > SMA(200) `Cl.gt.SMA200`
add.signal(strategy        =          strategy.st, 
           name            =          "sigComparison", 
           arguments       =          list(columns        =  c("Close",
                                                               "SMA200"), 
                                           relationship   =  "gt"), 
           label           =          "Cl.gt.SMA200")

# Add signal for when RSI2.lt.5 and Cl.gt.SMA200 are TRUE `BTO`
add.signal(strategy        =          strategy.st, 
           name            =          "sigFormula", 
           arguments       =          list(formula = "RSI2.lt.5 & Cl.gt.SMA200",
                                           cross = TRUE), 
           label           =          "BTO")

# Close > SMA(5) `STC`
add.signal(strategy        =          strategy.st, 
           name            =          "sigComparison", 
           arguments       =          list(columns         =    c("Close", 
                                                                  "SMA5"), 
                                           relationship    =    "gt"), 
           label           =          "STC")

sig <- applySignals(strategy = strategy.st, 
                    mktdata  = ind)
```

## Add Rules

```{r add.rules}
# BTO `shares` shares at market price, preferably on Close.
add.rule(strategy       =    strategy.st,
         name           =    "ruleSignal",
         arguments      =    list(sigcol        =    "BTO",
                                  sigval        =    TRUE,
                                  orderqty      =    shares,
                                  ordertype     =    "market",
                                  orderside     =    "long", 
                                  prefer        =    "Close", 
                                  # Deduce transactions fees
                                  TxnFees       =    abs(transaction_fees) * -1,
                                  osFUN = osMaxPos, 
                                  # Do not replace any existing orders
                                  replace       =    FALSE),
         type           =    "enter",
         # Var indicating order
         label          =    "Long")

# Liquidate when `STC` is TURE
add.rule(strategy.st, 
         name           = "ruleSignal", 
         arguments      = list(sigcol           =    "STC", 
                               sigval           =    TRUE, 
                               orderside        =    "long", 
                               ordertype        =    "market", 
                               orderqty         =    "all", 
                               TxnFees          =    abs(transaction_fees) * -1,
                               # Replace existing orders
                               replace          =    TRUE), 
         type           = "exit", 
         label          = "Exit2SHORT")

```

## Add Position Limit

```{r position.limits}
for(symbol in symbols){
    addPosLimit(portfolio = portfolio.st,
                symbol    = symbol,
                timestamp = init_date,
                maxpos    = shares)
}
```

## Apply Strategy

```{r apply.strategy, results = "hide"}
# Apply strategy
applyStrategy(strategy.st, 
              portfolios          =         portfolio.st)
```

## Update Portfolio and Account objects

```{r update.objects}
updatePortf(portfolio.st)
updateAcct(account.st)
updateEndEq(account.st)
```

## Validate Portfolio vs Account

```{r checkBlotterUpdate}
checkBlotterUpdate(portfolio.st, 
                   account.st, 
                   verbose        =         TRUE)
```

## Chart Positions

```{r chart.posn}
# Print charts for each symbol showing transactions, PnL, Drawdown
# Assign to x to suppress R output
x <- map(symbols, 
         chart.Posn, 
         Portfolio      =    portfolio.st, 
         TA             =    paste(sprintf("add_SMA(n = %d, col = %d)", 
                                           smaFast, 
                                           smaFastCol),
                                   sprintf("add_SMA(n = %d, col = %d)", 
                                           smaSlow, 
                                           smaSlowCol),
                                   sprintf("add_RSI(n = %d, maType = %s)",
                                           nrsi,
                                           rsiMaType),
                                   sep = ";"))
```

## Trade Analysis

```{r tstats}
tstats <- tradeStats(portfolio.st)
kable(t(tstats))
```

## Cash Sharpe Ratio

```{r portfolio.sharpe}
portfolio.pnl <- .blotter$portfolio.ConnorsRSI$summary$Net.Trading.PL
SharpeRatio.annualized(R         = portfolio.pnl, 
                       geometric = FALSE)
```

```{r instrument.sharpe}
instrument.returns <- PortfReturns(portfolio.st)
SharpeRatio.annualized(R         = instrument.returns, 
                       geometric = FALSE)
```

## Performance Summary

```{r}
returns <- PortfReturns(Account = account.st)
rownames(returns) <- NULL
charts.PerformanceSummary(returns, 
                          colorset = bluefocus)
```

## Portfolio Summary

```{r}
port <- getPortfolio(portfolio.st)
xyplot(x      =    port$summary, 
       type   =    "h", 
       col    =    4)
```

## Session Info

```{r sessioninfo, echo = FALSE, child="_sessioninfo.Rmd"}
```
